Added yaml.encode and a few test cases for it
vadv/gopher-lua-libs pull request #18
Opened 2020-12-26 08:14 UTC by scr-oath

2020-12-28 12:08 UTC, vadv requested changes
thanks 🙏 
please upgrade readme && rebase with master

2020-12-28 12:08 UTC, vadv commented on yaml/api.go
> +	"fmt"
please update via golang.org/x/tools/cmd/goimports

2020-12-28 22:06 UTC, scr-oath commented on yaml/api.go
> +	"fmt"
Done

2020-12-28 22:08 UTC, scr-oath commented
Updated readme

2020-12-28 22:58 UTC, scr-oath commented
> thanks 🙏
> please upgrade readme && rebase with master

Done

2020-12-29 15:31 UTC, vadv approved these changes

2020-12-29 15:32 UTC, merged